//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDescriptor.h"

@implementation ClassDescriptor

@synthesize radius;
@synthesize center;
- (void) dealloc {
	[center release];
	[super dealloc];
}

- (void) setRadiusWithReference: (int *) p_radius {
	radius = *p_radius;
}



@end

