//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDescriptor.h"

@implementation ClassDescriptor

@synthesize collectionOfCircles;
@synthesize yo;
- (void) dealloc {
	[collectionOfCircles release];
	[super dealloc];
}

- (void) setYoWithReference: (int *) p_yo {
	yo = *p_yo;
}



@end

