//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDescriptor.h"

@implementation ClassDescriptor

@synthesize x;
@synthesize y;
- (void) dealloc {
	[super dealloc];
}

- (void) setXWithReference: (int *) p_x {
	x = *p_x;
}

- (void) setYWithReference: (int *) p_y {
	y = *p_y;
}



@end

