//
//  Faculty.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "Person.h"


/*!
	@class		Faculty
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface Faculty : Person
{
	/*!
		@var		designation
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *designation;

}

@property (nonatomic, readwrite, retain) NSString *designation;


@end

