//
//  Faculty.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Faculty.h"

@implementation Faculty

@synthesize designation;
- (void) dealloc {
	[designation release];
	[super dealloc];
}



@end

