//
//  Person.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Person.h"

@implementation Person

@synthesize name;
- (void) dealloc {
	[name release];
	[super dealloc];
}



@end

