//
//  Student.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/03/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Student.h"

@implementation Student

@synthesize stuNum;
- (void) dealloc {
	[stuNum release];
	[super dealloc];
}



@end

