//
//  Channel.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Channel.h"

@implementation Channel

@synthesize items;
@synthesize title;
@synthesize description;
@synthesize link;
- (void) dealloc {
	[items release];
	[title release];
	[description release];
	[link release];
	[super dealloc];
}



@end

