//
//  Item.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Item.h"

@implementation Item

@synthesize title;
@synthesize description;
@synthesize link;
@synthesize guid;
@synthesize author;
- (void) dealloc {
	[title release];
	[description release];
	[link release];
	[guid release];
	[author release];
	[super dealloc];
}



@end

