//
//  Rss.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "Channel.h"


/*!
	@class		Rss
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface Rss
{
	/*!
		@var		version
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	float version;

	/*!
		@var		channel
		@abstract	Annotated as : 
					@simpl_composite
		@discussion	missing java doc comments or could not find the source file.
	*/
	Channel *channel;

}

@property (nonatomic, readwrite) float version;
@property (nonatomic, readwrite, retain) Channel *channel;

- (void) setVersionWithReference: (float *) p_version;

@end

