#import "TranslationScope.h"
#import "Point.h"
#import "Person.h"
#import "Circle.h"
#import "Point.h"
#import "CollectionOfCircles.h"
#import "Student.h"
#import "Person.h"
#import "Circle.h"
#import "Point.h"
#import "Rss.h"
#import "Channel.h"
#import "Item.h"
#import "Circle.h"
#import "Point.h"
#import "Faculty.h"
#import "Person.h"

#import <Foundation/Foundation.h>


/*!
	@class		rss
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface rss
{
}

+ (TranslationScope *) translationScope;


@end

