//
//  Circle.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/03/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Circle.h"

@implementation Circle

@synthesize radius;
@synthesize center;
- (void) dealloc {
	[center release];
	[super dealloc];
}

- (void) setRadiusWithReference: (int *) p_radius {
	radius = *p_radius;
}



@end

