//
//  CollectionOfCircles.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 11/07/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "CollectionOfCircles.h"

@implementation CollectionOfCircles

@synthesize collectionOfCircles;
@synthesize yo;
- (void) dealloc {
	[collectionOfCircles release];
	[super dealloc];
}

- (void) setYoWithReference: (int *) p_yo {
	yo = *p_yo;
}



@end

