//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDescriptor.h"

@implementation ClassDescriptor

@synthesize items;
@synthesize title;
@synthesize description;
@synthesize link;
- (void) dealloc {
	[items release];
	[title release];
	[description release];
	[link release];
	[super dealloc];
}



@end

