//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDescriptor.h"

@implementation ClassDescriptor

@synthesize title;
@synthesize description;
@synthesize link;
@synthesize guid;
@synthesize author;
- (void) dealloc {
	[title release];
	[description release];
	[link release];
	[guid release];
	[author release];
	[super dealloc];
}



@end

