//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ElementState.h"
#import "ParsedURL.h"
#import "ParsedURL.h"


/*!
	@class		Item
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface Item : ElementState
{
	/*!
		@var		title
		@abstract	Annotated as : 
					@simpl_scalar
					@simpl_hints
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *title;

	/*!
		@var		description
		@abstract	Annotated as : 
					@simpl_scalar
					@simpl_hints
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *description;

	/*!
		@var		link
		@abstract	Annotated as : 
					@simpl_scalar
					@simpl_hints
		@discussion	missing java doc comments or could not find the source file.
	*/
	ParsedURL *link;

	/*!
		@var		guid
		@abstract	Annotated as : 
					@simpl_scalar
					@simpl_hints
		@discussion	missing java doc comments or could not find the source file.
	*/
	ParsedURL *guid;

	/*!
		@var		author
		@abstract	Annotated as : 
					@simpl_scalar
					@simpl_hints
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *author;

}

@property (nonatomic, readwrite, retain) NSString *title;
@property (nonatomic, readwrite, retain) NSString *description;
@property (nonatomic, readwrite, retain) ParsedURL *link;
@property (nonatomic, readwrite, retain) ParsedURL *guid;
@property (nonatomic, readwrite, retain) NSString *author;


@end

