//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDescriptor.h"

@implementation ClassDescriptor

@synthesize version;
@synthesize channel;
- (void) dealloc {
	[channel release];
	[super dealloc];
}

- (void) setVersionWithReference: (float *) p_version {
	version = *p_version;
}



@end

