#import "TranslationScope.h"
#import "Point.h"
#import "Circle.h"
#import "Point.h"

#import <Foundation/Foundation.h>


/*!
	@class		circleTypeScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface circleTypeScope
{
}

+ (TranslationScope *) translationScope;


@end

