#import "SimplTypesScope.h"
#import "Point.h"
#import "Circle.h"

#import <Foundation/Foundation.h>


/*!
	@class		circleTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface circleTScope
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

