#import "SimplTypesScope.h"
#import "ClassDescriptor.h"
#import "ClassDescriptor.h"
#import "ClassDescriptor.h"

#import <Foundation/Foundation.h>


/*!
	@class		circleTypeScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface circleTypeScope
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

