#import "SimplTypesScope.h"
#import "Point.h"
#import "CollectionOfCircles.h"
#import "Circle.h"

#import <Foundation/Foundation.h>


/*!
	@class		collectionOfCirclesTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface collectionOfCirclesTScope
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

