#import "SimplTypesScope.h"
#import "Point.h"

#import <Foundation/Foundation.h>


/*!
	@class		pointTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface pointTScope
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

