#import "SimplTypesScope.h"
#import "Item.h"
#import "Rss.h"
#import "Channel.h"

#import <Foundation/Foundation.h>


/*!
	@class		rss
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface rss
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

